// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJJBafyww8kMnJ32TZ2Ok0i6IXTE0PTWs',
    appId: '1:212639165124:android:fb0e2bcba9cc69c495b791',
    messagingSenderId: '212639165124',
    projectId: 'ndvpn-flutter',
    databaseURL: 'https://ndvpn-flutter-default-rtdb.firebaseio.com',
    storageBucket: 'ndvpn-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_eLvlGruM-cdyJdmkVp-gwZv0iastXmI',
    appId: '1:212639165124:ios:cac5dc1cd1d9099895b791',
    messagingSenderId: '212639165124',
    projectId: 'ndvpn-flutter',
    databaseURL: 'https://ndvpn-flutter-default-rtdb.firebaseio.com',
    storageBucket: 'ndvpn-flutter.appspot.com',
    androidClientId: '212639165124-okjk6jrivtm8btuuo6h4eldnl3gcavnh.apps.googleusercontent.com',
    iosClientId: '212639165124-jv52buhcmn0h1poahb2hjeqs7oednqct.apps.googleusercontent.com',
    iosBundleId: 'com.ndvpn.ios.app',
  );
}
